spring.application.name=carofly_game_server
#spring.main.web-application-type=none
# Forces the application context to stay active even without a web server
spring.main.keep-alive=true
#Spring(OpenAI) Config
spring.ai.ppenai.api-key= $vck_5UK4yR7HCVMzlpwVhphMso3ADzLHa2Dif7SOkyeISJjSmzOhyz2p167z
spring.ai.ppenai.chat.options= spring.ai.ppenai.
spring.ai.ppenai.chat.model=gpt-4o spring.ai.ppenai.
spring.ai.ppenai.chat.temperature= 0.7 spring.ai.ppenai.
#
#spring.cloud.gcp.firestore.emulator.enabled=true
#spring.cloud.gcp.project-id="carofly-714e0"
## Set the host and port of your running Firestore emulator
#spring.cloud.gcp.firestore.host-port=localhost:9090
#firebase.config.path=${FIREBASE_CONFIG_PATH:classpath:serviceAccountKey.json}
#
#firebase.database.url=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40carofly-714e0.iam.gserviceaccount.com

# application.properties

#port=9090
##//FireBase Config
## Enable connection to the local emulator suite



#firebase.config.path=



# (Required) Match the project-id you set when initializing the emulator


# Path to the JSON file you downloaded from Firebase Console

#
## Your Firebase Database URL (find this in the Realtime Database tab)

##spring.datasource.sql="