spring.application.name=carofly_game_server
port=9090
#//FireBase Config
#GOOGLE_CLOUD_SERVICES="carofly-2a3d0"
#GOOGLE_APPLICATION_CREDENTIALS="103HUlutIm1K_BPpIKDLypfUncyExpaYn7H4zweEzO8"
# Path to the JSON file you downloaded from Firebase Console
#firebase.config.path=classpath:serviceAccountKey.json
#
## Your Firebase Database URL (find this in the Realtime Database tab)
#firebase.database.url=https://your-project-id-default-rtdb.firebaseio.com/
##spring.datasource.sql="